{"hospital_name": "A K G Memorial Co Operative Hospital", "address": "Talap, Kannur - 670002, Kerala", "director": null, "email": null, "phone": null, "mobile": null}
{"hospital_name": "5 Elements Clinic", "address": "972/S Panorama Arcade  Edappally, Ernakulam - 682024, Kerala", "director": "Dr Samreth", "email": "drsamreth009@yahoo.com", "phone": "9387920008", "mobile": null}
{"hospital_name": "Tanushree Female Hospital", "address": "84, Chiklol Road, Near Petrol Pump, Bhopal - 462008, Madhya Pradesh", "director": null, "email": null, "phone": "0755-2766966", "mobile": null}
{"hospital_name": "32 Pearls Multispeciality Dental Clinic", "address": "Vennala  Vennala, Kochi - 682028, Kerala", "director": null, "email": "32pearlsmdc@gmail.com", "phone": "9995592292", "mobile": null}
{"hospital_name": "Arogyam Panchkarma Centre & Ayurvedic Hospital", "address": "Arogyam Panchkarma Centre & Ayurvedic Hospital, Opp.Police Station, Mehatpur (una, Una - 174303, Himachal Pradesh", "director": "Sukriti sharma", "email": "sukritisharma205@gmail.com", "phone": "919805038733, +919356306733", "mobile": null}
{"hospital_name": "Comfort Eyecare Opticians & Clinic", "address": "Shop No 8 L & L Odyssey Building Navelim Road Margao  Navelim Road Margao, Goa - 403601, Goa", "director": "Mavis Archangel Lucy", "email": null, "phone": "832-2728333, 9881287757", "mobile": null}
{"hospital_name": "Colva Dental Clinic", "address": "Shop No-25 Colva Church Complex  Colva, Goa - 403708, Goa", "director": null, "email": "colvadentalclinicgoa@gmail.com", "phone": "832-2788513, 9822125930", "mobile": null}
{"hospital_name": "A C N Hospital", "address": "3 A New Vishawas Nagar Quarter Chowk Shahdara  Shahdara, Delhi - 110032, Delhi", "director": "Manoj", "email": "accounts@acngroup.in", "phone": "8010705040", "mobile": null}
{"hospital_name": "A B G Hospital", "address": "Moti Nager New Delhi-15, Delhi - 110015, Delhi", "director": "Ashu Goel", "email": null, "phone": "9463667694", "mobile": null}
{"hospital_name": "The Care (uttarpara Nursing Home)", "address": "27/T, R.K. Street, Uttarpara, Hooghly - 712245, West Bengal", "director": null, "email": null, "phone": "033-26638018", "mobile": null}
{"hospital_name": "Temple Polyclinic", "address": "125 Ns Bose Road , Rajpur Kalitala, South 24 Parganas - 700149, West Bengal", "director": null, "email": null, "phone": null, "mobile": null}
{"hospital_name": "The Amala Arogya Niketan & Polyclinic", "address": "P.O : Rupnarayan Pur Bazar, Bardhaman - 713101, West Bengal", "director": null, "email": null, "phone": "033-24668529", "mobile": null}
{"hospital_name": "Swarupananda Nursing Home", "address": "Keshiary, Paschim Medinipur, Purba Medinipur, Purba Medinipur - 721636, West Bengal", "director": null, "email": null, "phone": "03220-245728", "mobile": null}
{"hospital_name": "Swadesh Basu Hospital", "address": "204A, Diamond Harbour Rd, Thakurpukur, Kolkata - 700063, West Bengal", "director": null, "email": null, "phone": "033-24674006", "mobile": null}
{"hospital_name": "Susruta Clinic & Research Institute For Advance", "address": "Jc 16 - 17, Sector 3, Salt Lake City, Kolkata, Kolkata \t - 700098, West Bengal", "director": null, "email": null, "phone": "033-23351299", "mobile": null}
{"hospital_name": "Swastik Seva Sadan", "address": "No. 16C  Topsia ,Tiljala, Kolkata - 700046, West Bengal", "director": null, "email": null, "phone": null, "mobile": null}
{"hospital_name": "Susrut Eye Foundation & Research Centre - Berhampore", "address": "HB-36/A/1, Sec.-III, Salt Lake City, Kolkata - 700106, West Bengal", "director": null, "email": null, "phone": "033-23341628", "mobile": null}
{"hospital_name": "Susama Tripathy Memorial Nursing Home", "address": "Jhaljhalia Malda, Malda - 732101, West Bengal", "director": null, "email": null, "phone": "03512-265490", "mobile": null}
{"hospital_name": "Sri Durga Maternity Cum Nursing Home", "address": "Baragarh, Debra Bazar,,Nh-6- To Balichak Railway Station, Paschim Medinipur - 721126, West Bengal", "director": null, "email": null, "phone": "03226-243449", "mobile": null}
{"hospital_name": "Second Sight Southend Eye Hospital", "address": "Dhopagachi-P-O-Kundarali-Baruipur, South 24 Parganas - 743610, West Bengal", "director": null, "email": null, "phone": "033-24230541", "mobile": null}
{"hospital_name": "Sunetra Eye & Family Care Centre", "address": "1050/1, Eastern Metropolitan Bypass, Survey Park, Santoshpur, Kolkata - 700075, West Bengal", "director": null, "email": null, "phone": "033-24188223", "mobile": null}
{"hospital_name": "Recovery Nursing Home P Ltd", "address": "15/1 Jatindra Mohan Avenue, Bankura - 700006, West Bengal", "director": null, "email": null, "phone": "033-2533527", "mobile": null}
{"hospital_name": "Ranaghat Lions Eye Care Center-rsby", "address": "Biswaspara, Po. Ranaghat, Near Sporting Club, Nadia - 741201, West Bengal", "director": null, "email": null, "phone": "3473-210778", "mobile": null}
{"hospital_name": "34 Heart Care", "address": "G 80, Vikas Marg, Preet Vihar, Delhi - 110092, Delhi", "director": "Sumit Gupta", "email": "help@34care.com", "phone": "91-11-7065359704, 91-7065359703", "mobile": null}
{"hospital_name": "32 White Pearls Dental Clinic", "address": "C-7/57 Main Market Keshav Puram Opposite Pipal Wala Mandir  Keshav Puram, Delhi - 110035, Delhi", "director": "Nishita", "email": "32whitepearls14@gmail.com", "phone": "7503688085", "mobile": null}
{"hospital_name": "32 Pearls Multispeciality Dental Clinic", "address": "G-15 Single Story  Vijay Nagar Near Delhi University, Delhi - 110009, Delhi", "director": null, "email": "appointment@32pearlsdentalclinic.com", "phone": "9999955440", "mobile": null}
{"hospital_name": "Shreya Dental & Gynae Clinic", "address": "28-B, Pocket-1, Sector 7, Dwarka, Delhi - 110075, Delhi", "director": null, "email": "dr.jarora23@gmail.com", "phone": "91-9152301362, 91-9810009109", "mobile": null}
{"hospital_name": "Shah's Clinic", "address": "507, Navniti Apt, Patparganj, 51,I P Extn,Nr Taravati Medical Centre, Delhi - 110092, Delhi", "director": null, "email": "narayanshah@rediffmail.com", "phone": "1122246457, 91-9810113623", "mobile": null}
{"hospital_name": "Neurotherapy Clinic", "address": "Sanatan Dharam Mandir, Vikaspuri, J Block, Delhi - 110018, Delhi", "director": null, "email": "skpathak260@gmail.com", "phone": "91-9868762470, 91-9971727065", "mobile": null}
{"hospital_name": "Liberal Clinic", "address": "A - 1/79, Main Road, Rohini, Delhi - 110085, Delhi", "director": null, "email": "lioberal.clinic@gmail.com", "phone": "91-9891487334", "mobile": null}
{"hospital_name": "Jeevan Herbal Clinic & Research Centre", "address": "shop no 20 B lane no 1, Shanti nagar extension, Krishna Nagar, near welcome metro station, Delhi - 110051, Delhi", "director": null, "email": null, "phone": "91-8368376212, 91-9212715182", "mobile": null}
{"hospital_name": "Ilakkiya Homeopathic Clinic", "address": "3/118, Shop Number-6, Ground Floor, Subhash Nagar, Near Aggrawal Sweets, Delhi - 110027, Delhi", "director": null, "email": "dr.rahul.wal@gmail.com", "phone": "1125148263, 91-9212148848", "mobile": null}
{"hospital_name": "Chopra Homeopathic Clinic", "address": "A-20 Puspanjali Enclave, Pitampura, Delhi - 110034, Delhi", "director": null, "email": "homoeoremedies@gmail.com", "phone": "91-9811653870", "mobile": null}
{"hospital_name": "Brij Hormone Lab And Thyroid Center", "address": "24, Ansari Road, Darya Ganj, Delhi - 110002, Delhi", "director": null, "email": "sanjeevanhospitals@gmail.com", "phone": "11-45770000, 91-9560795268", "mobile": null}
{"hospital_name": "Amri Hospital", "address": "230 Barkohala Lane Mukundapur-Kalikapur Behind Metro Cash And Carry  Kalikapur, Kolkata - 700099, West Bengal", "director": "Suparna Paul", "email": "corp.comm@amrihospitals.in, suparnapaul80@gmail.com", "phone": "33-44125558, 9836122067", "mobile": null}
{"hospital_name": "Omkar Homeo Clinic", "address": "Shop No. -12, Bal Uidhyan Rd, Param Puri-Uttam Nagar, Near West Metro Station, Uttam Nafgae, Delhi - 110059, Delhi", "director": null, "email": null, "phone": "91-8800976097, 91-9654162282", "mobile": null}
{"hospital_name": "Malik Clinic", "address": "Chalera Gao, Sector 44,  Near Hdfc Atm, Delhi - 201303, Delhi", "director": null, "email": null, "phone": "91-9990227571, 91-8826454362", "mobile": null}
{"hospital_name": "Cam Clinic", "address": "NORTH GOA GOA  pakim aadares nager, Goa - 403201, Goa", "director": "Cam", "email": null, "phone": "8326454485", "mobile": null}
{"hospital_name": "Bone Joint And Spine Clinic", "address": "102 Kamat Centre 1st floor D B Marg  Panjim, Goa - 403001, Goa", "director": "Mahendra", "email": null, "phone": "832-2462980, 9822101506", "mobile": null}
{"hospital_name": "Al-hayat Multispeciality Hospital & Gynae Care", "address": "F-625, 25 Futa Road, Jaitpur Extension, Delhi - 110044, Delhi", "director": null, "email": null, "phone": "1165383803, 91-9835200710", "mobile": null}
{"hospital_name": "Apollo Victor Hospitals Margaon", "address": "Malbhat, Margao, Goa - 403601, Goa", "director": null, "email": "info@apollovictorhospital.com", "phone": "832-2728888, 2725725, 2726272, 9372196868, 9822119616", "mobile": null}
{"hospital_name": "Anil Da Silva Dental Clinic", "address": "1st FloorResort Park Avenue Calangute Baga Road Calangute Near Infantaria Bakery Baga\\n, Goa - 403516, Goa", "director": null, "email": "renukadoc@hotmail.com", "phone": "832-6528794, 9326130111", "mobile": null}
{"hospital_name": "Apollo Victor Hospital", "address": "Malbhat Margao  Malbhat, Goa - 403601, Goa", "director": "Victor Albuquerque", "email": "info@apollovictorhospital.com", "phone": "832-6728888, 7508309390", "mobile": null}
{"hospital_name": "Anandi Nursing Home And Maternity Hospital", "address": "Marcel, Orgao, Goa - 403107, Goa", "director": "Dr Vinayak", "email": "drvinayakgarde@yahoo.in", "phone": "91-9822120775", "mobile": null}
{"hospital_name": "Ambika Dental Clinic", "address": "Palang Building Near Gram Panchayat Marcela  Palang Building, Goa - 433107, Goa", "director": "Ambika Ambor", "email": "rajanlambhor@rediffmail.com", "phone": "832-2288784, 9823642034", "mobile": null}
{"hospital_name": "Ais Clinic", "address": "AIS Clinic 2nd Floor Glass Tower Opp Traffic Cell Panjim  Panjim, Goa - 403001, Goa", "director": "Vishal Verenkar", "email": "drvishalverenkar@yahoo.co.in", "phone": "8806728287", "mobile": null}
{"hospital_name": "Aditya Minimal Access Surgical Clinic", "address": "3rd Floor Karmallys Glass Tower  Panjim Opposite Traffic Cell Near Geeta Bakery, Goa - 403001, Goa", "director": "Merry", "email": null, "phone": "7774099011", "mobile": null}
{"hospital_name": "Acupuncture Clinic", "address": "Gff 2a Technocidade Chogm Road Porvorim, Goa - 403521, Goa", "director": "Geeta Kalangutkar", "email": null, "phone": "832-2410802, 9923966403", "mobile": null}
{"hospital_name": "Sai Krishna Maternity Home", "address": "tokarkhada Road, Samarvarni, silvassa, Dadra and Nagar Haveli - 396230, Gujarat", "director": null, "email": null, "phone": "0260-653 4604", "mobile": null}
{"hospital_name": "32 Pearls Dental Clinic", "address": "Flat No 3 1st Floor Silent Retreate Naika VaddoOpposite Royal FoodsCalangute Calangute\\n, Goa - 403516, Goa", "director": "Ajit", "email": "ajit12.2008@rediffmail.com, shindeajit32@gmail.com", "phone": "9975333937", "mobile": null}
{"hospital_name": "Mukta General Hospital And Maternity Home", "address": "Behind Primary School, Zanda Chowk, Dadra & Nagar Haveli, Dadra and Nagar Haveli - 396230, Dadra and Nagar Haveli", "director": "Nill", "email": null, "phone": null, "mobile": null}
{"hospital_name": "Hari Om Hospital", "address": "Naroli Road, Near D C Bank, OppositeHotel Natraj, Dadra and Nagar Haveli - 396230, Dadra and Nagar Haveli", "director": null, "email": null, "phone": null, "mobile": null}
{"hospital_name": "Aproopa Nursing Home", "address": "Shreedar Estate,OppositeAmil Dena Bank Near Fire Station Piperia, Vapi Main Road, Dadra and Nagar Haveli - 396230, Dadra and Nagar Haveli", "director": null, "email": null, "phone": null, "mobile": null}
{"hospital_name": "Dr. Nikams Sri Sai Marigold Child Care Hospital And N I C U", "address": "Daffodil Blg, Iti Road, Amli Juction,Nr. Sai Mandir, Dadra and Nagar Haveli - 396230, Dadra and Nagar Haveli", "director": null, "email": null, "phone": null, "mobile": null}
{"hospital_name": "Apollo Hospital", "address": "Lingyadih Road, Seepat Road, Bilaspur - 495006, Himachal Pradesh", "director": "Shrirang Kale", "email": "ceo@apollohospitalsbilaspur.com", "phone": "7752-248300,7752-433433, 9752850336", "mobile": null}
{"hospital_name": "Apex Diagnostics", "address": "Near Netaji Park, Hospital Road, Solan - 173212, Himachal Pradesh", "director": "Dr. Raj Kumar Gandhi", "email": "contact@apexdiagnostics.in", "phone": "91-8894781113, 91-8894781112", "mobile": null}
{"hospital_name": "Darshan Eye Hospital", "address": "Solanki Complex Opp Town Hall, Dadra and Nagar Haveli - 396230, Dadra and Nagar Haveli", "director": null, "email": null, "phone": "0260    2643465, 264215", "mobile": null}
{"hospital_name": "Altis Hospital", "address": "Auckland Complex Hamirpur Road, Una - 174303, Himachal Pradesh", "director": null, "email": "altishospital1@gmail.com", "phone": "9418002030", "mobile": null}
{"hospital_name": "Apna Hospital", "address": "Ghagas, - Nh - 21, Manali Road, Bilaspur - 174001, Himachal Pradesh", "director": null, "email": null, "phone": null, "mobile": null}
{"hospital_name": "Agnihotri Life Line Hospital", "address": "Near Bus Stand, Una - 174302, Himachal Pradesh", "director": null, "email": null, "phone": null, "mobile": null}
{"hospital_name": "Advanced Dental Care Clinic", "address": "Shop No. 14  Ground Floor  Rajeev Gandhi Complex. Museum Road  \\n, Chamba - 176310, Himachal Pradesh", "director": "Manik Mahajan", "email": "mnkmhjn@gmail.com", "phone": "9736186411", "mobile": null}
{"hospital_name": "Aastha Hospital & Paediatricians Centre", "address": "Pantha GhatiKusumpti  Kusumpti, Shimla - 171002, Himachal Pradesh", "director": "Roshan", "email": "roshan16@gmail.com", "phone": "9418050377", "mobile": null}
{"hospital_name": "Aastha Maternity Home And Taruma Centre", "address": "Rana Complex ,Near Chowk, Mandi - 175008, Himachal Pradesh", "director": null, "email": null, "phone": null, "mobile": null}
{"hospital_name": "32 Pearls Implant & Orthodentic Dental Hospital", "address": "Tahliwal Nangal Road Santokgarh  Santokhgarh, Una - 174301, Himachal Pradesh", "director": "Aman Prashar", "email": "dramanprashar32@gmail.com, dramanprashar@gmail.com", "phone": "1975-225854, 9418787080", "mobile": null}
{"hospital_name": "Aakash Hospital And Diagnostics", "address": "Opp Radha Swami Satsang Bhawan Rakh Ram Singh , Pinjore Road Nalagarh, Solan - 173205, Himachal Pradesh", "director": null, "email": null, "phone": null, "mobile": null}
{"hospital_name": "Aakash Hospital", "address": "Nalagarh, Solan, Himachal Pradesh", "director": null, "email": null, "phone": null, "mobile": null}
{"hospital_name": "Sushruta Hospital", "address": "Lake View Colony,Dhadiyal,Sundr Nagar, Mandi - 175001, Himachal Pradesh", "director": null, "email": null, "phone": null, "mobile": null}
{"hospital_name": "Sushma Hospital And Women Care Centre", "address": "Lohna Colony, Near K.L.B. College, Palampur, Kangra - 176061, Himachal Pradesh", "director": null, "email": null, "phone": "01894-230830", "mobile": null}
{"hospital_name": "Sri Ram Hospital", "address": "18-D,Lane-4,Sector-1, Shimla - 171001, Himachal Pradesh", "director": null, "email": null, "phone": "0177-2645889", "mobile": null}
{"hospital_name": "S R Hospital & Surgical Center", "address": "Nh-21, Vill. Kalheli- P. O Bajaura- Tehshil, Kullu - 175125, Himachal Pradesh", "director": null, "email": null, "phone": "1903-266564", "mobile": null}
{"hospital_name": "Kristu Jyoti Hospital", "address": "National Highway, 1-A Diani, Samba, Jammu and Kashmir - 184121, Jammu and Kashmir", "director": null, "email": null, "phone": null, "mobile": null}
{"hospital_name": "Kalindi Hospital And Diagnostic Centre", "address": "2/155, Vikas Nagar Subash Nagar, Jammu and Kashmir - 180005, Jammu and Kashmir", "director": null, "email": null, "phone": null, "mobile": null}
